SELECT * FROM SOCIOS;
SELECT * FROM DEPORTES;
SELECT * FROM INSCRIPTOS;

SELECT S.* FROM SOCIOS S
INNER JOIN INSCRIPTOS I
ON S.DOCUMENTO = I.DOCUMENTO
INNER JOIN DEPORTES D
ON D.CODIGO = I.CODIGODEPORTE;

CREATE TABLE TBL_A(
 ID NUMBER PRIMARY KEY,
 DATO_UNO VARCHAR2(25) DEFAULT 'DATO UNO',
 DATO_DOS VARCHAR2(25) DEFAULT 'DATO DOS'
);

CREATE TABLE TBL_B(
 ID NUMBER PRIMARY KEY,
 ID_A NUMBER,
 DATO_UNO VARCHAR2(25) DEFAULT 'DATO UNO',
 DATO_DOS VARCHAR2(25) DEFAULT 'DATO DOS'
);

CREATE TABLE TBL_C(
 ID NUMBER PRIMARY KEY,
 ID_B NUMBER,
 DATO_UNO VARCHAR2(25) DEFAULT 'DATO UNO',
 DATO_DOS VARCHAR2(25) DEFAULT 'DATO DOS'
);

INSERT INTO TBL_A (ID) VALUES(1);
INSERT INTO TBL_A (ID) VALUES(2);
INSERT INTO TBL_A (ID) VALUES(3);
INSERT INTO TBL_A (ID) VALUES(4);

INSERT INTO TBL_B (ID, ID_A) VALUES(1,1);
INSERT INTO TBL_B (ID, ID_A) VALUES(2,2);
INSERT INTO TBL_B (ID, ID_A) VALUES(3,3);
INSERT INTO TBL_B (ID, ID_A) VALUES(4,0);

INSERT INTO TBL_C (ID, ID_B) VALUES(1,1);
INSERT INTO TBL_C (ID, ID_B) VALUES(2,2);
INSERT INTO TBL_C (ID, ID_B) VALUES(3,0);

SELECT * FROM TBL_A;
SELECT * FROM TBL_B;
SELECT * FROM TBL_C;

SELECT * FROM TBL_A A
INNER JOIN TBL_B B
ON A.ID = B.ID_A
INNER JOIN TBL_C C
ON C.ID_B = B.ID;
